### ISSUE TITLE
Installation guide 

### ISSUE THREAD

**Issue by dariushm2** [linuxdeepin/deepin-system-monitor#12]
I saw this amazing system monitor on your distro, Deepin and I was hooked. Wanted to try it on my Ubuntu machine but the installation guide wasn't helpful enough. Googled for a more thorough guideline with no result. 

Given that your own distro is based on Debian, is it possible for you to release a deb package or at least explain a better installation guide?

**Comment by thepante** [comment]
I don't if you got it working, but here I put the steps for someone who is searching for it. 
I'm using ubuntu 18.10 with gnome.  

**First all dependencies needed**  

```bash
sudo apt install libpcap-dev libncurses5-dev libprocps-dev libxtst-dev libxcb-util0-dev qttools5-dev-tools libdtkwidget-dev libdtkwm-dev
```
**Then the steps**  

```bash
git clone https://github.com/linuxdeepin/deepin-system-monitor.git
cd deepin-system-monitor
mkdir build && cd build
qmake ..
make
sudo setcap cap_kill,cap_net_raw,cap_dac_read_search,cap_sys_ptrace+ep ./deepin-system-monitor
```

**Done, you can run it**
```bash
./deepin-system-monitor
```
**So now, it runs ok? so close it, let's put this in /opt and add the .desktop file:**

```bash
cd .. && mv build /opt/deepin-system-monitor
mv deepin-system-monitor.desktop ~/.local/share/applications/deepin-system-monitor.desktop
gedit ~/.local/share/applications/deepin-system-monitor.desktop
```

There edit the line `Exec=deepin-system-monitor` for the correct path: `Exec=/opt/deepin-system-monitor/deepin-system-monitor`
**Completly done, we can delete the repo folder that we clone in first step.**

---

Now that I had tried this app, I have the urge to try that DE haha

**Comment by icydresden** [comment]
> sudo apt install libpcap-dev libncurses5-dev libprocps-dev libxtst-dev libxcb-util0-dev qttools5-dev-tools libdtkwidget-dev libdtkwm-dev

Could tell us, which qmake version did you use?

**Comment by icydresden** [comment]
maybe helpful to solve problem
[deepin system monitor](https://github.com/linuxdeepin/deepin-system-monitor/issues/22)

**Comment by coreybruce** [comment]
Still having the same issue

https://i.imgur.com/Lu9HQQD.png

**Comment by lixuedong1024** [comment]
> Still had the same issue, the issues is it's missing a depedancy which can be fixed by doing `sudo apt-get install qt5-default`
> 
> please add this to the list of dependencies..

This is useful Thank you

**Comment by ElianVanCutsem** [comment]
This should be marked as closed.
